import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
import * as model from '../public/world-model.js';import * as sharing from '../public/world-share.js';
const brief={world:'A counting game',actors:['Player'],resources:['Tokens'],rules:['Start with no tokens. Take one token at a time.'],rubric:['Hold at most one token.']};
const analysis={mode:'simulation',explanation:'A bounded token count',assumptions:['At most two tokens in this model'],variables:[{id:'tokens',label:'Tokens',values:[0,1,2],initial:0}],actions:[{id:'take',label:'Take a token',ruleIndexes:[0],when:true,effects:[{variable:'tokens',add:1}]}],criteria:[{rubricIndex:0,holds:{variable:'tokens',op:'lte',value:1}}]};
function creator(){const nodes=new Map();let exported,shared;
 function element(id){if(!nodes.has(id))nodes.set(id,{value:'',textContent:'',innerHTML:'',hidden:false,disabled:false,handlers:{},addEventListener(k,fn){this.handlers[k]=fn;},setAttribute(){},querySelectorAll(){return [];},focus(){},scrollIntoView(){}});return nodes.get(id);}
 class TestURL extends URL{static createObjectURL(blob){exported=blob;return 'blob:test';}static revokeObjectURL(){}}
 const context=vm.createContext({...model,...sharing,URL:TestURL,URLSearchParams,Blob,structuredClone,location:{hash:'',origin:'http://localhost'},navigator:{clipboard:{async writeText(s){shared=s;}}},document:{getElementById:element,querySelectorAll:()=>[],createElement:()=>({click(){}})},window:{addEventListener(){}},setTimeout(){}});
 vm.runInContext(readFileSync(new URL('../public/create.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,''),context);
 const run=code=>vm.runInContext(code,context);context.bundle={brief,analysis};return {element,run,exported:()=>exported,shared:()=>shared};
}
test('applying a generated model runs the actual search and manual counterexamples survive a revision',()=>{const a=creator();a.run('activate(bundle)');assert.equal(a.run('result.found'),true);a.element('manual-reset').handlers.click();a.run("manualMove('take');manualMove('take')");assert.match(a.element('result').innerHTML,/Your moves break/);a.run("const fixed=structuredClone(bundle);fixed.analysis.actions[0].when={variable:'tokens',op:'lt',value:1};activate(fixed)");assert.equal(a.run('result.found'),false);assert.equal(a.run('previous.trace.length'),2);a.element('replay-previous').handlers.click();assert.equal(a.run('trace.at(-1).allowed'),false);});
test('critique has no simulation verdict and replacing it does not retain stale simulation evidence',()=>{const a=creator();a.run('activate(bundle)');a.run("activate({brief:bundle.brief,analysis:{mode:'review',explanation:'Needs judgment',assessments:[{rubricIndex:0,status:'needs_clarification',scenario:'A possible issue',reasoning:'A definition is missing.',suggestedRevision:'Define success.'}]}})");assert.equal(a.run('result'),null);assert.equal(a.run('trace.length'),0);assert.match(a.element('result').innerHTML,/not an executed simulation/);assert.equal(a.element('simulation').hidden,true);assert.equal(a.element('critique').hidden,false);});
test('editing the brief invalidates a pending model but leaves the applied model intact',()=>{const a=creator();a.run('activate(bundle);proposal=bundle;draftChanged()');assert.equal(a.run('proposal'),null);assert.equal(a.run('applied.brief.world'),brief.world);assert.equal(a.element('apply').disabled,true);assert.match(a.element('applied-note').textContent,/have not changed/);});
test('new speech without a structured draft cannot replace the previous draft speech provenance',()=>{const a=creator();a.run("showBrief(bundle.brief,'First source',{text:'First recording'});speech={text:'Later failed extraction'}");assert.equal(a.run('briefSpeech.text'),'First recording');assert.equal(a.run('briefEdited'),false);a.run('draftChanged()');assert.equal(a.run('briefEdited'),true);});
test('shared world excludes speech and exported evidence retains the reviewed model and result',async()=>{const a=creator();a.run("activate({...bundle,speech:{text:'Original voice'},briefEdited:true})");await a.element('share').handlers.click();const fragment=new URLSearchParams(new URL(a.shared()).hash.slice(1));const shared=sharing.decodeWorld(fragment.get('world'));assert.equal('speech' in shared,false);await a.element('export').handlers.click();const out=JSON.parse(await a.exported().text());assert.equal(out.applied.briefEdited,true);assert.equal(out.applied.speech.text,'Original voice');assert.equal(out.result.found,true);});
test('a new shared-world fragment replaces the displayed world without a provider call',()=>{const a=creator();a.run("location.hash='#world='+encodeWorld({version:1,...bundle});loadSharedWorld()");assert.equal(a.run('applied.source'),'Shared world');assert.equal(a.run('result.found'),true);assert.match(a.element('message').textContent,/No new AssemblyAI request/);});
