import test from 'node:test';import assert from 'node:assert/strict';import {transcribe,gateway} from '../services.mjs';
test('dictation sends the current API shape and retains raw text on cleanup failure',async()=>{
 const original=globalThis.fetch;
 try{globalThis.fetch=async(url,options)=>{assert.equal(url,'https://dictation.assemblyai.com/transcribe');const configPart=options.body.get('config');assert.equal(configPart.type,'application/json');const config=JSON.parse(await configPart.text());assert.equal(typeof config.llm_instruction,'string');assert.equal(config.sample_rate,16000);assert.equal(config.channels,1);assert.ok(!('word_boost' in config));assert.ok(!('llm' in config));return Response.json({text:'Do not open for red.',llm_response:null,llm_error:'timeout'});};const r=await transcribe(new Uint8Array(8000),{ASSEMBLYAI_API_KEY:'test-key'});assert.equal(r.cleaned,r.text);assert.equal(r.cleanupAvailable,false);}finally{globalThis.fetch=original;}
});
test('gateway rate limits leave an actionable retry response',async()=>{const original=globalThis.fetch;try{globalThis.fetch=async()=>new Response('{}',{status:429});await assert.rejects(gateway('a custom rule',{ASSEMBLYAI_API_KEY:'test-key'}),e=>e.status===429&&e.message.includes('Wait a minute'));}finally{globalThis.fetch=original;}});
test('intentional empty cleanup stays empty instead of restoring fillers',async()=>{const original=globalThis.fetch;try{globalThis.fetch=async()=>Response.json({text:'Um, uh.',llm_response:'',llm_error:null});const r=await transcribe(new Uint8Array(8000),{ASSEMBLYAI_API_KEY:'test-key'});assert.equal(r.cleaned,'');assert.equal(r.cleanupAvailable,true);}finally{globalThis.fetch=original;}});
test('a reported cleanup failure never presents returned text as successful cleanup',async()=>{const original=globalThis.fetch;try{globalThis.fetch=async()=>Response.json({text:'Do not approve.',llm_response:'Approve.',llm_error:'failed'});const r=await transcribe(new Uint8Array(8000),{ASSEMBLYAI_API_KEY:'test-key'});assert.equal(r.cleaned,'Do not approve.');assert.equal(r.cleanupAvailable,false);}finally{globalThis.fetch=original;}});
test('unsupported rules and malformed provider output have distinct HTTP errors',async()=>{const original=globalThis.fetch;try{for(const [content,status] of [[JSON.stringify({supported:false,reason:'Timers are not supported.'}),422],['not json',502],[JSON.stringify({supported:true,policy:{},assumptions:[]}),502]]){globalThis.fetch=async()=>Response.json({choices:[{message:{content}}]});await assert.rejects(gateway('A rule',{ASSEMBLYAI_API_KEY:'test-key'},'coupons'),e=>e.status===status);}}finally{globalThis.fetch=original;}});
