import test from 'node:test';import assert from 'node:assert/strict';
import {validateBrief,validateAnalysis,worldInitial,worldStep,worldSearch,worldReplay,worldViolations} from '../public/world-model.js';
import {encodeWorld,decodeWorld} from '../public/world-share.js';
const brief={world:'A shared observatory dome',actors:['Caretaker'],resources:['Roof','Rain sensor'],rules:['The roof starts closed. It may be opened or closed at any time.','Rain starts absent and may begin or stop at any time.'],rubric:['The roof must stay closed while it rains.']};
const eq=(variable,value)=>({variable,op:'eq',value});
const raw={mode:'simulation',explanation:'Two independently changing conditions.',assumptions:['One roof; rain is a boolean.'],variables:[{id:'roof',label:'Roof open',values:[false,true],initial:false},{id:'rain',label:'Raining',values:[false,true],initial:false}],actions:[{id:'open',label:'Open roof',ruleIndexes:[0],when:true,effects:[{variable:'roof',set:true}]},{id:'close',label:'Close roof',ruleIndexes:[0],when:true,effects:[{variable:'roof',set:false}]},{id:'rain',label:'Rain starts',ruleIndexes:[1],when:true,effects:[{variable:'rain',set:true}]},{id:'dry',label:'Rain stops',ruleIndexes:[1],when:true,effects:[{variable:'rain',set:false}]}],criteria:[{rubricIndex:0,holds:{not:{all:[eq('roof',true),eq('rain',true)]}}}]};
const fresh=()=>structuredClone(raw);
test('a user-defined world has a replayable counterexample independent of preset domains',()=>{const model=validateAnalysis(raw,brief),r=worldSearch(model);assert.equal(r.found,true);assert.equal(r.trace.length,2);assert.deepEqual(worldReplay(model,r.trace),r.trace);assert.deepEqual(r.violations,[0]);assert.deepEqual(worldInitial(model),{roof:false,rain:false});});
test('changed guards block the original moves without inventing new replay actions',()=>{const original=worldSearch(validateAnalysis(raw,brief));const fixed=fresh();fixed.actions[0].when=eq('rain',false);fixed.actions[2].effects.push({variable:'roof',set:false});const model=validateAnalysis(fixed,brief);assert.equal(worldSearch(model).found,false);const replay=worldReplay(model,original.trace);assert.deepEqual(replay.map(t=>t.action),original.trace.map(t=>t.action));assert.deepEqual(worldViolations(model,replay.at(-1).state),[]);});
test('search limits produce an inconclusive result and initial violations need zero moves',()=>{const model=validateAnalysis(raw,brief);assert.equal(worldSearch(model,{maxStates:1}).exhaustive,false);assert.equal(worldSearch(model,{maxDepth:1}).truncated,true);const initial=fresh();initial.variables.forEach(v=>v.initial=true);const r=worldSearch(validateAnalysis(initial,brief));assert.equal(r.found,true);assert.equal(r.trace.length,0);});
test('out-of-range effects stop at the model boundary without mutating state',()=>{const model=validateAnalysis({mode:'simulation',explanation:'A bounded counter',assumptions:[],variables:[{id:'count',label:'Count',values:[0,1,2],initial:0}],actions:[{id:'add',label:'Add one',ruleIndexes:[0],when:true,effects:[{variable:'count',add:1}]}],criteria:[{rubricIndex:0,holds:{variable:'count',op:'lte',value:1}}]},{...brief,rules:['Add items.']});const state={count:2};const blocked=worldStep(model,state,'add');assert.equal(blocked.allowed,false);assert.equal(blocked.boundary,true);assert.deepEqual(state,{count:2});assert.deepEqual(blocked.state,state);});
test('models must cover all rules and rubric items and use valid data-only operations',()=>{
 const invalids=[];let m=fresh();m.criteria=[];invalids.push(m);m=fresh();m.actions=m.actions.filter(a=>a.ruleIndexes[0]===0);invalids.push(m);m=fresh();m.actions[0].effects=[{variable:'missing',set:true}];invalids.push(m);m=fresh();m.actions[0].when={variable:'roof',op:'execute',value:true};invalids.push(m);m=fresh();m.criteria[0].holds=true;invalids.push(m);m=fresh();m.variables[0].id='constructor';invalids.push(m);m=fresh();m.actions[0].effects.push({variable:'roof',set:false});invalids.push(m);
 for(const invalid of invalids)assert.throws(()=>validateAnalysis(invalid,brief));
});
test('critique preserves every rubric item and cannot declare a proven pass',()=>{const review={mode:'review',explanation:'Requires judgment',assessments:[{rubricIndex:0,status:'needs_clarification',scenario:'A visitor dislikes the outcome.',reasoning:'The criterion is subjective.',suggestedRevision:'Define observable measures.'}]};assert.equal(validateAnalysis(review,brief).mode,'review');assert.throws(()=>validateAnalysis({...review,assessments:[]},brief));assert.throws(()=>validateAnalysis({...review,assessments:[{...review.assessments[0],status:'passed'}]},brief));});
test('world links round-trip arbitrary names and validated models but exclude transcripts and receipts',()=>{const input={version:1,brief:{...brief,world:'Observatoire partagé · 月'},analysis:raw,speech:{text:'Private original speech'},receipt:{requestId:'private'}};const decoded=decodeWorld(encodeWorld(input));assert.equal(decoded.brief.world,input.brief.world);assert.equal('speech' in decoded,false);assert.equal('receipt' in decoded,false);assert.equal(worldSearch(decoded.analysis).found,true);assert.throws(()=>decodeWorld('invalid!'));});
test('incomplete briefs stay editable while analysis requires current rules and a rubric',()=>{const incomplete={world:'My new world',actors:[],resources:[],rules:[],rubric:[]};assert.deepEqual(validateBrief(incomplete),incomplete);assert.throws(()=>validateBrief(incomplete,{complete:true}));assert.throws(()=>validateBrief({...incomplete,extra:true}));});
